title: Understand Backend Development with Python and Django
description: >-
  A guide for beginners who are looking forward to get an extensive knowledge in
  web development as far as backend development is concerned. This course
  teaches you different web development concepts and techniques using the Python
  and Django. 
template:
  repo: understand-backend-development-with-python-and-django-template
  name: understand-backend-development-with-python-and-django
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
